spring.application.name=config-server
server.port=8888

# Use local filesystem no Git needed
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/configs

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.org.springframework.cloud.config=DEBUG
