spring.application.name=blood-supply-service

server.port=8003

spring.datasource.url=jdbc:mysql://localhost:3306/blood-supply-service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=goutham007

# Tells Spring to use the MySQL Connector/J driver to speak the "MySQL language.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true


app.jwt.secret=donorConnectSuperSecretKey2024@donorConnectSuperSecretKey2024
app.jwt.expiration=86400000


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=method

#Shows you very detailed logs for your code
logging.level.com.donorconnect.bloodsupplyservice=DEBUG
#Only shows important security events (like successful logins), hiding the boring details
logging.level.org.springframework.security=INFO

app.pagination.default-page=0
app.pagination.default-size=20

app.expiry.warning-days=3


# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}


# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
#spring.application.name=blood-supply-service
#
#server.port=8003
#
#spring.datasource.url=jdbc:mysql://localhost:3306/blood-supply-service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
#
## Tells Spring to use the MySQL Connector/J driver to speak the "MySQL language.
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.format_sql=true
#
#
#app.jwt.secret=donorConnectSuperSecretKey2024@donorConnectSuperSecretKey2024
#app.jwt.expiration=86400000
#
#
#springdoc.api-docs.path=/v1/api-docs
#springdoc.swagger-ui.path=/swagger-ui/index.html
#springdoc.swagger-ui.operationsSorter=method
#
##Shows you very detailed logs for your code
#logging.level.com.donorconnect.bloodsupplyservice=DEBUG
##Only shows important security events (like successful logins), hiding the boring details
#logging.level.org.springframework.security=INFO
#
#app.pagination.default-page=0
#app.pagination.default-size=20
#
#app.expiry.warning-days=3
#
#
## Eureka Client Configuration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true
#eureka.instance.instance-id=${spring.application.name}:${server.port}
#
#
## Actuator
#management.endpoints.web.exposure.include=health
#management.endpoint.health.show-details=always

spring.application.name=blood-supply-service
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.fail-fast=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
