# Server
server.port=8006

  # Database
spring.datasource.url=jdbc:mysql://localhost:3306/project_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

  # JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

  # JWT Secret (Base64-encoded 256-bit key ? replace with your actual shared secret)
jwt.secret=dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGp3dCBzaWduaW5nIHB1cnBvc2Vz

  # Razorpay Payment Gateway
razorpay.key.id=rzp_test_SfcQEhmmgO4M85
razorpay.key.secret=fuVmpQJ1HpfxybKzg0YQUj9c

  # Pagination default
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100
spring.cloud.compatibility-verifier.enabled=false


spring.Application.name=billing-service



eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}