# =============================================
# SHARED CONFIG applied to ALL services
# =============================================

# JWT
app.jwt.secret=donorConnectSuperSecretKey2024@donorConnectSuperSecretKey2024
app.jwt.expiration=86400000

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Pagination
app.pagination.default-page=0
app.pagination.default-size=20

# Springdoc
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
